// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.24.4
// source: core/contract/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceCode int32

const (
	ResourceCode_BANDWIDTH  ResourceCode = 0
	ResourceCode_ENERGY     ResourceCode = 1
	ResourceCode_TRON_POWER ResourceCode = 2
)

// Enum value maps for ResourceCode.
var (
	ResourceCode_name = map[int32]string{
		0: "BANDWIDTH",
		1: "ENERGY",
		2: "TRON_POWER",
	}
	ResourceCode_value = map[string]int32{
		"BANDWIDTH":  0,
		"ENERGY":     1,
		"TRON_POWER": 2,
	}
)

func (x ResourceCode) Enum() *ResourceCode {
	p := new(ResourceCode)
	*p = x
	return p
}

func (x ResourceCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceCode) Descriptor() protoreflect.EnumDescriptor {
	return file_core_contract_common_proto_enumTypes[0].Descriptor()
}

func (ResourceCode) Type() protoreflect.EnumType {
	return &file_core_contract_common_proto_enumTypes[0]
}

func (x ResourceCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceCode.Descriptor instead.
func (ResourceCode) EnumDescriptor() ([]byte, []int) {
	return file_core_contract_common_proto_rawDescGZIP(), []int{0}
}

var File_core_contract_common_proto protoreflect.FileDescriptor

var file_core_contract_common_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2a, 0x39, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x41, 0x4e, 0x44, 0x57, 0x49,
	0x44, 0x54, 0x48, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x4e, 0x45, 0x52, 0x47, 0x59, 0x10,
	0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x52, 0x4f, 0x4e, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x10,
	0x02, 0x42, 0x45, 0x0a, 0x18, 0x6f, 0x72, 0x67, 0x2e, 0x74, 0x72, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5a, 0x29, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x6f, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_contract_common_proto_rawDescOnce sync.Once
	file_core_contract_common_proto_rawDescData = file_core_contract_common_proto_rawDesc
)

func file_core_contract_common_proto_rawDescGZIP() []byte {
	file_core_contract_common_proto_rawDescOnce.Do(func() {
		file_core_contract_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_contract_common_proto_rawDescData)
	})
	return file_core_contract_common_proto_rawDescData
}

var file_core_contract_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_contract_common_proto_goTypes = []interface{}{
	(ResourceCode)(0), // 0: protocol.ResourceCode
}
var file_core_contract_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_contract_common_proto_init() }
func file_core_contract_common_proto_init() {
	if File_core_contract_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_contract_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_contract_common_proto_goTypes,
		DependencyIndexes: file_core_contract_common_proto_depIdxs,
		EnumInfos:         file_core_contract_common_proto_enumTypes,
	}.Build()
	File_core_contract_common_proto = out.File
	file_core_contract_common_proto_rawDesc = nil
	file_core_contract_common_proto_goTypes = nil
	file_core_contract_common_proto_depIdxs = nil
}
