// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.24.4
// source: core/contract/shield_contract.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []bool `protobuf:"varint,1,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *AuthenticationPath) Reset() {
	*x = AuthenticationPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_shield_contract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationPath) ProtoMessage() {}

func (x *AuthenticationPath) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_shield_contract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationPath.ProtoReflect.Descriptor instead.
func (*AuthenticationPath) Descriptor() ([]byte, []int) {
	return file_core_contract_shield_contract_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticationPath) GetValue() []bool {
	if x != nil {
		return x.Value
	}
	return nil
}

type MerklePath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthenticationPaths []*AuthenticationPath `protobuf:"bytes,1,rep,name=authentication_paths,json=authenticationPaths,proto3" json:"authentication_paths,omitempty"`
	Index               []bool                `protobuf:"varint,2,rep,packed,name=index,proto3" json:"index,omitempty"`
	Rt                  []byte                `protobuf:"bytes,3,opt,name=rt,proto3" json:"rt,omitempty"`
}

func (x *MerklePath) Reset() {
	*x = MerklePath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_shield_contract_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerklePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerklePath) ProtoMessage() {}

func (x *MerklePath) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_shield_contract_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerklePath.ProtoReflect.Descriptor instead.
func (*MerklePath) Descriptor() ([]byte, []int) {
	return file_core_contract_shield_contract_proto_rawDescGZIP(), []int{1}
}

func (x *MerklePath) GetAuthenticationPaths() []*AuthenticationPath {
	if x != nil {
		return x.AuthenticationPaths
	}
	return nil
}

func (x *MerklePath) GetIndex() []bool {
	if x != nil {
		return x.Index
	}
	return nil
}

func (x *MerklePath) GetRt() []byte {
	if x != nil {
		return x.Rt
	}
	return nil
}

type OutputPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash  []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index int32  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *OutputPoint) Reset() {
	*x = OutputPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_shield_contract_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputPoint) ProtoMessage() {}

func (x *OutputPoint) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_shield_contract_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputPoint.ProtoReflect.Descriptor instead.
func (*OutputPoint) Descriptor() ([]byte, []int) {
	return file_core_contract_shield_contract_proto_rawDescGZIP(), []int{2}
}

func (x *OutputPoint) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *OutputPoint) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type OutputPointInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutPoints []*OutputPoint `protobuf:"bytes,1,rep,name=out_points,json=outPoints,proto3" json:"out_points,omitempty"`
	BlockNum  int32          `protobuf:"varint,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
}

func (x *OutputPointInfo) Reset() {
	*x = OutputPointInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_shield_contract_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputPointInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputPointInfo) ProtoMessage() {}

func (x *OutputPointInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_shield_contract_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputPointInfo.ProtoReflect.Descriptor instead.
func (*OutputPointInfo) Descriptor() ([]byte, []int) {
	return file_core_contract_shield_contract_proto_rawDescGZIP(), []int{3}
}

func (x *OutputPointInfo) GetOutPoints() []*OutputPoint {
	if x != nil {
		return x.OutPoints
	}
	return nil
}

func (x *OutputPointInfo) GetBlockNum() int32 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

type PedersenHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *PedersenHash) Reset() {
	*x = PedersenHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_shield_contract_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PedersenHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedersenHash) ProtoMessage() {}

func (x *PedersenHash) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_shield_contract_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedersenHash.ProtoReflect.Descriptor instead.
func (*PedersenHash) Descriptor() ([]byte, []int) {
	return file_core_contract_shield_contract_proto_rawDescGZIP(), []int{4}
}

func (x *PedersenHash) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type IncrementalMerkleTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left    *PedersenHash   `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right   *PedersenHash   `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	Parents []*PedersenHash `protobuf:"bytes,3,rep,name=parents,proto3" json:"parents,omitempty"`
}

func (x *IncrementalMerkleTree) Reset() {
	*x = IncrementalMerkleTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_shield_contract_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementalMerkleTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementalMerkleTree) ProtoMessage() {}

func (x *IncrementalMerkleTree) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_shield_contract_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementalMerkleTree.ProtoReflect.Descriptor instead.
func (*IncrementalMerkleTree) Descriptor() ([]byte, []int) {
	return file_core_contract_shield_contract_proto_rawDescGZIP(), []int{5}
}

func (x *IncrementalMerkleTree) GetLeft() *PedersenHash {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *IncrementalMerkleTree) GetRight() *PedersenHash {
	if x != nil {
		return x.Right
	}
	return nil
}

func (x *IncrementalMerkleTree) GetParents() []*PedersenHash {
	if x != nil {
		return x.Parents
	}
	return nil
}

type IncrementalMerkleVoucher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tree        *IncrementalMerkleTree `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	Filled      []*PedersenHash        `protobuf:"bytes,2,rep,name=filled,proto3" json:"filled,omitempty"`
	Cursor      *IncrementalMerkleTree `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	CursorDepth int64                  `protobuf:"varint,4,opt,name=cursor_depth,json=cursorDepth,proto3" json:"cursor_depth,omitempty"`
	Rt          []byte                 `protobuf:"bytes,5,opt,name=rt,proto3" json:"rt,omitempty"`
	OutputPoint *OutputPoint           `protobuf:"bytes,10,opt,name=output_point,json=outputPoint,proto3" json:"output_point,omitempty"`
}

func (x *IncrementalMerkleVoucher) Reset() {
	*x = IncrementalMerkleVoucher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_shield_contract_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementalMerkleVoucher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementalMerkleVoucher) ProtoMessage() {}

func (x *IncrementalMerkleVoucher) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_shield_contract_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementalMerkleVoucher.ProtoReflect.Descriptor instead.
func (*IncrementalMerkleVoucher) Descriptor() ([]byte, []int) {
	return file_core_contract_shield_contract_proto_rawDescGZIP(), []int{6}
}

func (x *IncrementalMerkleVoucher) GetTree() *IncrementalMerkleTree {
	if x != nil {
		return x.Tree
	}
	return nil
}

func (x *IncrementalMerkleVoucher) GetFilled() []*PedersenHash {
	if x != nil {
		return x.Filled
	}
	return nil
}

func (x *IncrementalMerkleVoucher) GetCursor() *IncrementalMerkleTree {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *IncrementalMerkleVoucher) GetCursorDepth() int64 {
	if x != nil {
		return x.CursorDepth
	}
	return 0
}

func (x *IncrementalMerkleVoucher) GetRt() []byte {
	if x != nil {
		return x.Rt
	}
	return nil
}

func (x *IncrementalMerkleVoucher) GetOutputPoint() *OutputPoint {
	if x != nil {
		return x.OutputPoint
	}
	return nil
}

type IncrementalMerkleVoucherInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vouchers []*IncrementalMerkleVoucher `protobuf:"bytes,1,rep,name=vouchers,proto3" json:"vouchers,omitempty"`
	Paths    [][]byte                    `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *IncrementalMerkleVoucherInfo) Reset() {
	*x = IncrementalMerkleVoucherInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_shield_contract_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementalMerkleVoucherInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementalMerkleVoucherInfo) ProtoMessage() {}

func (x *IncrementalMerkleVoucherInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_shield_contract_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementalMerkleVoucherInfo.ProtoReflect.Descriptor instead.
func (*IncrementalMerkleVoucherInfo) Descriptor() ([]byte, []int) {
	return file_core_contract_shield_contract_proto_rawDescGZIP(), []int{7}
}

func (x *IncrementalMerkleVoucherInfo) GetVouchers() []*IncrementalMerkleVoucher {
	if x != nil {
		return x.Vouchers
	}
	return nil
}

func (x *IncrementalMerkleVoucherInfo) GetPaths() [][]byte {
	if x != nil {
		return x.Paths
	}
	return nil
}

type SpendDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValueCommitment         []byte `protobuf:"bytes,1,opt,name=value_commitment,json=valueCommitment,proto3" json:"value_commitment,omitempty"`
	Anchor                  []byte `protobuf:"bytes,2,opt,name=anchor,proto3" json:"anchor,omitempty"`       // merkle root
	Nullifier               []byte `protobuf:"bytes,3,opt,name=nullifier,proto3" json:"nullifier,omitempty"` // used for check double spend
	Rk                      []byte `protobuf:"bytes,4,opt,name=rk,proto3" json:"rk,omitempty"`               // used for check spend authority signature
	Zkproof                 []byte `protobuf:"bytes,5,opt,name=zkproof,proto3" json:"zkproof,omitempty"`
	SpendAuthoritySignature []byte `protobuf:"bytes,6,opt,name=spend_authority_signature,json=spendAuthoritySignature,proto3" json:"spend_authority_signature,omitempty"`
}

func (x *SpendDescription) Reset() {
	*x = SpendDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_shield_contract_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpendDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendDescription) ProtoMessage() {}

func (x *SpendDescription) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_shield_contract_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendDescription.ProtoReflect.Descriptor instead.
func (*SpendDescription) Descriptor() ([]byte, []int) {
	return file_core_contract_shield_contract_proto_rawDescGZIP(), []int{8}
}

func (x *SpendDescription) GetValueCommitment() []byte {
	if x != nil {
		return x.ValueCommitment
	}
	return nil
}

func (x *SpendDescription) GetAnchor() []byte {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *SpendDescription) GetNullifier() []byte {
	if x != nil {
		return x.Nullifier
	}
	return nil
}

func (x *SpendDescription) GetRk() []byte {
	if x != nil {
		return x.Rk
	}
	return nil
}

func (x *SpendDescription) GetZkproof() []byte {
	if x != nil {
		return x.Zkproof
	}
	return nil
}

func (x *SpendDescription) GetSpendAuthoritySignature() []byte {
	if x != nil {
		return x.SpendAuthoritySignature
	}
	return nil
}

type ReceiveDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValueCommitment []byte `protobuf:"bytes,1,opt,name=value_commitment,json=valueCommitment,proto3" json:"value_commitment,omitempty"`
	NoteCommitment  []byte `protobuf:"bytes,2,opt,name=note_commitment,json=noteCommitment,proto3" json:"note_commitment,omitempty"`
	Epk             []byte `protobuf:"bytes,3,opt,name=epk,proto3" json:"epk,omitempty"`               // for Encryption
	CEnc            []byte `protobuf:"bytes,4,opt,name=c_enc,json=cEnc,proto3" json:"c_enc,omitempty"` // Encryption for incoming, decrypt it with ivk
	COut            []byte `protobuf:"bytes,5,opt,name=c_out,json=cOut,proto3" json:"c_out,omitempty"` // Encryption for audit, decrypt it with ovk
	Zkproof         []byte `protobuf:"bytes,6,opt,name=zkproof,proto3" json:"zkproof,omitempty"`
}

func (x *ReceiveDescription) Reset() {
	*x = ReceiveDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_shield_contract_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveDescription) ProtoMessage() {}

func (x *ReceiveDescription) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_shield_contract_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveDescription.ProtoReflect.Descriptor instead.
func (*ReceiveDescription) Descriptor() ([]byte, []int) {
	return file_core_contract_shield_contract_proto_rawDescGZIP(), []int{9}
}

func (x *ReceiveDescription) GetValueCommitment() []byte {
	if x != nil {
		return x.ValueCommitment
	}
	return nil
}

func (x *ReceiveDescription) GetNoteCommitment() []byte {
	if x != nil {
		return x.NoteCommitment
	}
	return nil
}

func (x *ReceiveDescription) GetEpk() []byte {
	if x != nil {
		return x.Epk
	}
	return nil
}

func (x *ReceiveDescription) GetCEnc() []byte {
	if x != nil {
		return x.CEnc
	}
	return nil
}

func (x *ReceiveDescription) GetCOut() []byte {
	if x != nil {
		return x.COut
	}
	return nil
}

func (x *ReceiveDescription) GetZkproof() []byte {
	if x != nil {
		return x.Zkproof
	}
	return nil
}

type ShieldedTransferContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransparentFromAddress []byte                `protobuf:"bytes,1,opt,name=transparent_from_address,json=transparentFromAddress,proto3" json:"transparent_from_address,omitempty"` // transparent address
	FromAmount             int64                 `protobuf:"varint,2,opt,name=from_amount,json=fromAmount,proto3" json:"from_amount,omitempty"`
	SpendDescription       []*SpendDescription   `protobuf:"bytes,3,rep,name=spend_description,json=spendDescription,proto3" json:"spend_description,omitempty"`
	ReceiveDescription     []*ReceiveDescription `protobuf:"bytes,4,rep,name=receive_description,json=receiveDescription,proto3" json:"receive_description,omitempty"`
	BindingSignature       []byte                `protobuf:"bytes,5,opt,name=binding_signature,json=bindingSignature,proto3" json:"binding_signature,omitempty"`
	TransparentToAddress   []byte                `protobuf:"bytes,6,opt,name=transparent_to_address,json=transparentToAddress,proto3" json:"transparent_to_address,omitempty"` // transparent address
	ToAmount               int64                 `protobuf:"varint,7,opt,name=to_amount,json=toAmount,proto3" json:"to_amount,omitempty"`                                      // the amount to transparent to_address
}

func (x *ShieldedTransferContract) Reset() {
	*x = ShieldedTransferContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_shield_contract_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShieldedTransferContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShieldedTransferContract) ProtoMessage() {}

func (x *ShieldedTransferContract) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_shield_contract_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShieldedTransferContract.ProtoReflect.Descriptor instead.
func (*ShieldedTransferContract) Descriptor() ([]byte, []int) {
	return file_core_contract_shield_contract_proto_rawDescGZIP(), []int{10}
}

func (x *ShieldedTransferContract) GetTransparentFromAddress() []byte {
	if x != nil {
		return x.TransparentFromAddress
	}
	return nil
}

func (x *ShieldedTransferContract) GetFromAmount() int64 {
	if x != nil {
		return x.FromAmount
	}
	return 0
}

func (x *ShieldedTransferContract) GetSpendDescription() []*SpendDescription {
	if x != nil {
		return x.SpendDescription
	}
	return nil
}

func (x *ShieldedTransferContract) GetReceiveDescription() []*ReceiveDescription {
	if x != nil {
		return x.ReceiveDescription
	}
	return nil
}

func (x *ShieldedTransferContract) GetBindingSignature() []byte {
	if x != nil {
		return x.BindingSignature
	}
	return nil
}

func (x *ShieldedTransferContract) GetTransparentToAddress() []byte {
	if x != nil {
		return x.TransparentToAddress
	}
	return nil
}

func (x *ShieldedTransferContract) GetToAmount() int64 {
	if x != nil {
		return x.ToAmount
	}
	return 0
}

var File_core_contract_shield_contract_proto protoreflect.FileDescriptor

var file_core_contract_shield_contract_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f,
	0x73, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22,
	0x2a, 0x0a, 0x12, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x0a,
	0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x4f, 0x0a, 0x14, 0x61, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x52, 0x13, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x03, 0x28, 0x08, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x72,
	0x74, 0x22, 0x37, 0x0a, 0x0b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x64, 0x0a, 0x0f, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a,
	0x0a, 0x6f, 0x75, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d,
	0x22, 0x28, 0x0a, 0x0c, 0x50, 0x65, 0x64, 0x65, 0x72, 0x73, 0x65, 0x6e, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xa3, 0x01, 0x0a, 0x15, 0x49,
	0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65,
	0x54, 0x72, 0x65, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x65,
	0x64, 0x65, 0x72, 0x73, 0x65, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74,
	0x12, 0x2c, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x65, 0x64, 0x65, 0x72,
	0x73, 0x65, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x30,
	0x0a, 0x07, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x65, 0x64, 0x65, 0x72,
	0x73, 0x65, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x07, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0xa5, 0x02, 0x0a, 0x18, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x33, 0x0a,
	0x04, 0x74, 0x72, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x54, 0x72, 0x65, 0x65, 0x52, 0x04, 0x74, 0x72,
	0x65, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x65,
	0x64, 0x65, 0x72, 0x73, 0x65, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x6c,
	0x65, 0x64, 0x12, 0x37, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49, 0x6e,
	0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x54,
	0x72, 0x65, 0x65, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x5f, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x44, 0x65, 0x70, 0x74, 0x68, 0x12, 0x0e,
	0x0a, 0x02, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x72, 0x74, 0x12, 0x38,
	0x0a, 0x0c, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0b, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x74, 0x0a, 0x1c, 0x49, 0x6e, 0x63, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x56, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3e, 0x0a, 0x08, 0x76, 0x6f, 0x75, 0x63,
	0x68, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61,
	0x6c, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x08,
	0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x22, 0xd9,
	0x01, 0x0a, 0x10, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x75, 0x6c, 0x6c, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6e, 0x75, 0x6c, 0x6c, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x72, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x6b, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x7a, 0x6b, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x3a,
	0x0a, 0x19, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x17, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xbe, 0x01, 0x0a, 0x12, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x29, 0x0a, 0x10, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f,
	0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x70, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x65, 0x70, 0x6b, 0x12, 0x13, 0x0a, 0x05, 0x63, 0x5f, 0x65, 0x6e, 0x63,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x45, 0x6e, 0x63, 0x12, 0x13, 0x0a, 0x05,
	0x63, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x4f, 0x75,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x6b, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x7a, 0x6b, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x8d, 0x03, 0x0a, 0x18,
	0x53, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x38, 0x0a, 0x18, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x16, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x47, 0x0a, 0x11, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x73, 0x70, 0x65, 0x6e,
	0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4d, 0x0a, 0x13,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x12, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x11, 0x62,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x34, 0x0a, 0x16, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x14, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x6f, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x74, 0x6f, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x45, 0x0a, 0x18, 0x6f,
	0x72, 0x67, 0x2e, 0x74, 0x72, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_contract_shield_contract_proto_rawDescOnce sync.Once
	file_core_contract_shield_contract_proto_rawDescData = file_core_contract_shield_contract_proto_rawDesc
)

func file_core_contract_shield_contract_proto_rawDescGZIP() []byte {
	file_core_contract_shield_contract_proto_rawDescOnce.Do(func() {
		file_core_contract_shield_contract_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_contract_shield_contract_proto_rawDescData)
	})
	return file_core_contract_shield_contract_proto_rawDescData
}

var file_core_contract_shield_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_core_contract_shield_contract_proto_goTypes = []interface{}{
	(*AuthenticationPath)(nil),           // 0: protocol.AuthenticationPath
	(*MerklePath)(nil),                   // 1: protocol.MerklePath
	(*OutputPoint)(nil),                  // 2: protocol.OutputPoint
	(*OutputPointInfo)(nil),              // 3: protocol.OutputPointInfo
	(*PedersenHash)(nil),                 // 4: protocol.PedersenHash
	(*IncrementalMerkleTree)(nil),        // 5: protocol.IncrementalMerkleTree
	(*IncrementalMerkleVoucher)(nil),     // 6: protocol.IncrementalMerkleVoucher
	(*IncrementalMerkleVoucherInfo)(nil), // 7: protocol.IncrementalMerkleVoucherInfo
	(*SpendDescription)(nil),             // 8: protocol.SpendDescription
	(*ReceiveDescription)(nil),           // 9: protocol.ReceiveDescription
	(*ShieldedTransferContract)(nil),     // 10: protocol.ShieldedTransferContract
}
var file_core_contract_shield_contract_proto_depIdxs = []int32{
	0,  // 0: protocol.MerklePath.authentication_paths:type_name -> protocol.AuthenticationPath
	2,  // 1: protocol.OutputPointInfo.out_points:type_name -> protocol.OutputPoint
	4,  // 2: protocol.IncrementalMerkleTree.left:type_name -> protocol.PedersenHash
	4,  // 3: protocol.IncrementalMerkleTree.right:type_name -> protocol.PedersenHash
	4,  // 4: protocol.IncrementalMerkleTree.parents:type_name -> protocol.PedersenHash
	5,  // 5: protocol.IncrementalMerkleVoucher.tree:type_name -> protocol.IncrementalMerkleTree
	4,  // 6: protocol.IncrementalMerkleVoucher.filled:type_name -> protocol.PedersenHash
	5,  // 7: protocol.IncrementalMerkleVoucher.cursor:type_name -> protocol.IncrementalMerkleTree
	2,  // 8: protocol.IncrementalMerkleVoucher.output_point:type_name -> protocol.OutputPoint
	6,  // 9: protocol.IncrementalMerkleVoucherInfo.vouchers:type_name -> protocol.IncrementalMerkleVoucher
	8,  // 10: protocol.ShieldedTransferContract.spend_description:type_name -> protocol.SpendDescription
	9,  // 11: protocol.ShieldedTransferContract.receive_description:type_name -> protocol.ReceiveDescription
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_core_contract_shield_contract_proto_init() }
func file_core_contract_shield_contract_proto_init() {
	if File_core_contract_shield_contract_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_contract_shield_contract_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_shield_contract_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerklePath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_shield_contract_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_shield_contract_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputPointInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_shield_contract_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PedersenHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_shield_contract_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementalMerkleTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_shield_contract_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementalMerkleVoucher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_shield_contract_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementalMerkleVoucherInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_shield_contract_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpendDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_shield_contract_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_shield_contract_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShieldedTransferContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_contract_shield_contract_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_contract_shield_contract_proto_goTypes,
		DependencyIndexes: file_core_contract_shield_contract_proto_depIdxs,
		MessageInfos:      file_core_contract_shield_contract_proto_msgTypes,
	}.Build()
	File_core_contract_shield_contract_proto = out.File
	file_core_contract_shield_contract_proto_rawDesc = nil
	file_core_contract_shield_contract_proto_goTypes = nil
	file_core_contract_shield_contract_proto_depIdxs = nil
}
