// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.24.4
// source: core/contract/smart_contract.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SmartContract_ABI_Entry_EntryType int32

const (
	SmartContract_ABI_Entry_UnknownEntryType SmartContract_ABI_Entry_EntryType = 0
	SmartContract_ABI_Entry_Constructor      SmartContract_ABI_Entry_EntryType = 1
	SmartContract_ABI_Entry_Function         SmartContract_ABI_Entry_EntryType = 2
	SmartContract_ABI_Entry_Event            SmartContract_ABI_Entry_EntryType = 3
	SmartContract_ABI_Entry_Fallback         SmartContract_ABI_Entry_EntryType = 4
	SmartContract_ABI_Entry_Receive          SmartContract_ABI_Entry_EntryType = 5
	SmartContract_ABI_Entry_Error            SmartContract_ABI_Entry_EntryType = 6
)

// Enum value maps for SmartContract_ABI_Entry_EntryType.
var (
	SmartContract_ABI_Entry_EntryType_name = map[int32]string{
		0: "UnknownEntryType",
		1: "Constructor",
		2: "Function",
		3: "Event",
		4: "Fallback",
		5: "Receive",
		6: "Error",
	}
	SmartContract_ABI_Entry_EntryType_value = map[string]int32{
		"UnknownEntryType": 0,
		"Constructor":      1,
		"Function":         2,
		"Event":            3,
		"Fallback":         4,
		"Receive":          5,
		"Error":            6,
	}
)

func (x SmartContract_ABI_Entry_EntryType) Enum() *SmartContract_ABI_Entry_EntryType {
	p := new(SmartContract_ABI_Entry_EntryType)
	*p = x
	return p
}

func (x SmartContract_ABI_Entry_EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmartContract_ABI_Entry_EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_contract_smart_contract_proto_enumTypes[0].Descriptor()
}

func (SmartContract_ABI_Entry_EntryType) Type() protoreflect.EnumType {
	return &file_core_contract_smart_contract_proto_enumTypes[0]
}

func (x SmartContract_ABI_Entry_EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmartContract_ABI_Entry_EntryType.Descriptor instead.
func (SmartContract_ABI_Entry_EntryType) EnumDescriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type SmartContract_ABI_Entry_StateMutabilityType int32

const (
	SmartContract_ABI_Entry_UnknownMutabilityType SmartContract_ABI_Entry_StateMutabilityType = 0
	SmartContract_ABI_Entry_Pure                  SmartContract_ABI_Entry_StateMutabilityType = 1
	SmartContract_ABI_Entry_View                  SmartContract_ABI_Entry_StateMutabilityType = 2
	SmartContract_ABI_Entry_Nonpayable            SmartContract_ABI_Entry_StateMutabilityType = 3
	SmartContract_ABI_Entry_Payable               SmartContract_ABI_Entry_StateMutabilityType = 4
)

// Enum value maps for SmartContract_ABI_Entry_StateMutabilityType.
var (
	SmartContract_ABI_Entry_StateMutabilityType_name = map[int32]string{
		0: "UnknownMutabilityType",
		1: "Pure",
		2: "View",
		3: "Nonpayable",
		4: "Payable",
	}
	SmartContract_ABI_Entry_StateMutabilityType_value = map[string]int32{
		"UnknownMutabilityType": 0,
		"Pure":                  1,
		"View":                  2,
		"Nonpayable":            3,
		"Payable":               4,
	}
)

func (x SmartContract_ABI_Entry_StateMutabilityType) Enum() *SmartContract_ABI_Entry_StateMutabilityType {
	p := new(SmartContract_ABI_Entry_StateMutabilityType)
	*p = x
	return p
}

func (x SmartContract_ABI_Entry_StateMutabilityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmartContract_ABI_Entry_StateMutabilityType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_contract_smart_contract_proto_enumTypes[1].Descriptor()
}

func (SmartContract_ABI_Entry_StateMutabilityType) Type() protoreflect.EnumType {
	return &file_core_contract_smart_contract_proto_enumTypes[1]
}

func (x SmartContract_ABI_Entry_StateMutabilityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmartContract_ABI_Entry_StateMutabilityType.Descriptor instead.
func (SmartContract_ABI_Entry_StateMutabilityType) EnumDescriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

type SmartContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginAddress              []byte             `protobuf:"bytes,1,opt,name=origin_address,json=originAddress,proto3" json:"origin_address,omitempty"`
	ContractAddress            []byte             `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Abi                        *SmartContract_ABI `protobuf:"bytes,3,opt,name=abi,proto3" json:"abi,omitempty"`
	Bytecode                   []byte             `protobuf:"bytes,4,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	CallValue                  int64              `protobuf:"varint,5,opt,name=call_value,json=callValue,proto3" json:"call_value,omitempty"`
	ConsumeUserResourcePercent int64              `protobuf:"varint,6,opt,name=consume_user_resource_percent,json=consumeUserResourcePercent,proto3" json:"consume_user_resource_percent,omitempty"`
	Name                       string             `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	OriginEnergyLimit          int64              `protobuf:"varint,8,opt,name=origin_energy_limit,json=originEnergyLimit,proto3" json:"origin_energy_limit,omitempty"`
	CodeHash                   []byte             `protobuf:"bytes,9,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	TrxHash                    []byte             `protobuf:"bytes,10,opt,name=trx_hash,json=trxHash,proto3" json:"trx_hash,omitempty"`
	Version                    int32              `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *SmartContract) Reset() {
	*x = SmartContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_smart_contract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartContract) ProtoMessage() {}

func (x *SmartContract) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_smart_contract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartContract.ProtoReflect.Descriptor instead.
func (*SmartContract) Descriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{0}
}

func (x *SmartContract) GetOriginAddress() []byte {
	if x != nil {
		return x.OriginAddress
	}
	return nil
}

func (x *SmartContract) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *SmartContract) GetAbi() *SmartContract_ABI {
	if x != nil {
		return x.Abi
	}
	return nil
}

func (x *SmartContract) GetBytecode() []byte {
	if x != nil {
		return x.Bytecode
	}
	return nil
}

func (x *SmartContract) GetCallValue() int64 {
	if x != nil {
		return x.CallValue
	}
	return 0
}

func (x *SmartContract) GetConsumeUserResourcePercent() int64 {
	if x != nil {
		return x.ConsumeUserResourcePercent
	}
	return 0
}

func (x *SmartContract) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SmartContract) GetOriginEnergyLimit() int64 {
	if x != nil {
		return x.OriginEnergyLimit
	}
	return 0
}

func (x *SmartContract) GetCodeHash() []byte {
	if x != nil {
		return x.CodeHash
	}
	return nil
}

func (x *SmartContract) GetTrxHash() []byte {
	if x != nil {
		return x.TrxHash
	}
	return nil
}

func (x *SmartContract) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ContractState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnergyUsage  int64 `protobuf:"varint,1,opt,name=energy_usage,json=energyUsage,proto3" json:"energy_usage,omitempty"`
	EnergyFactor int64 `protobuf:"varint,2,opt,name=energy_factor,json=energyFactor,proto3" json:"energy_factor,omitempty"`
	UpdateCycle  int64 `protobuf:"varint,3,opt,name=update_cycle,json=updateCycle,proto3" json:"update_cycle,omitempty"`
}

func (x *ContractState) Reset() {
	*x = ContractState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_smart_contract_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractState) ProtoMessage() {}

func (x *ContractState) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_smart_contract_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractState.ProtoReflect.Descriptor instead.
func (*ContractState) Descriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{1}
}

func (x *ContractState) GetEnergyUsage() int64 {
	if x != nil {
		return x.EnergyUsage
	}
	return 0
}

func (x *ContractState) GetEnergyFactor() int64 {
	if x != nil {
		return x.EnergyFactor
	}
	return 0
}

func (x *ContractState) GetUpdateCycle() int64 {
	if x != nil {
		return x.UpdateCycle
	}
	return 0
}

type CreateSmartContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerAddress   []byte         `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	NewContract    *SmartContract `protobuf:"bytes,2,opt,name=new_contract,json=newContract,proto3" json:"new_contract,omitempty"`
	CallTokenValue int64          `protobuf:"varint,3,opt,name=call_token_value,json=callTokenValue,proto3" json:"call_token_value,omitempty"`
	TokenId        int64          `protobuf:"varint,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
}

func (x *CreateSmartContract) Reset() {
	*x = CreateSmartContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_smart_contract_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSmartContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSmartContract) ProtoMessage() {}

func (x *CreateSmartContract) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_smart_contract_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSmartContract.ProtoReflect.Descriptor instead.
func (*CreateSmartContract) Descriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSmartContract) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *CreateSmartContract) GetNewContract() *SmartContract {
	if x != nil {
		return x.NewContract
	}
	return nil
}

func (x *CreateSmartContract) GetCallTokenValue() int64 {
	if x != nil {
		return x.CallTokenValue
	}
	return 0
}

func (x *CreateSmartContract) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type TriggerSmartContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerAddress    []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ContractAddress []byte `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	CallValue       int64  `protobuf:"varint,3,opt,name=call_value,json=callValue,proto3" json:"call_value,omitempty"`
	Data            []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CallTokenValue  int64  `protobuf:"varint,5,opt,name=call_token_value,json=callTokenValue,proto3" json:"call_token_value,omitempty"`
	TokenId         int64  `protobuf:"varint,6,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
}

func (x *TriggerSmartContract) Reset() {
	*x = TriggerSmartContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_smart_contract_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerSmartContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSmartContract) ProtoMessage() {}

func (x *TriggerSmartContract) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_smart_contract_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSmartContract.ProtoReflect.Descriptor instead.
func (*TriggerSmartContract) Descriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerSmartContract) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *TriggerSmartContract) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *TriggerSmartContract) GetCallValue() int64 {
	if x != nil {
		return x.CallValue
	}
	return 0
}

func (x *TriggerSmartContract) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TriggerSmartContract) GetCallTokenValue() int64 {
	if x != nil {
		return x.CallTokenValue
	}
	return 0
}

func (x *TriggerSmartContract) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type ClearABIContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerAddress    []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ContractAddress []byte `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (x *ClearABIContract) Reset() {
	*x = ClearABIContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_smart_contract_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearABIContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearABIContract) ProtoMessage() {}

func (x *ClearABIContract) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_smart_contract_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearABIContract.ProtoReflect.Descriptor instead.
func (*ClearABIContract) Descriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{4}
}

func (x *ClearABIContract) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *ClearABIContract) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

type UpdateSettingContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerAddress               []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ContractAddress            []byte `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	ConsumeUserResourcePercent int64  `protobuf:"varint,3,opt,name=consume_user_resource_percent,json=consumeUserResourcePercent,proto3" json:"consume_user_resource_percent,omitempty"`
}

func (x *UpdateSettingContract) Reset() {
	*x = UpdateSettingContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_smart_contract_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSettingContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingContract) ProtoMessage() {}

func (x *UpdateSettingContract) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_smart_contract_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingContract.ProtoReflect.Descriptor instead.
func (*UpdateSettingContract) Descriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSettingContract) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *UpdateSettingContract) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *UpdateSettingContract) GetConsumeUserResourcePercent() int64 {
	if x != nil {
		return x.ConsumeUserResourcePercent
	}
	return 0
}

type UpdateEnergyLimitContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerAddress      []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ContractAddress   []byte `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	OriginEnergyLimit int64  `protobuf:"varint,3,opt,name=origin_energy_limit,json=originEnergyLimit,proto3" json:"origin_energy_limit,omitempty"`
}

func (x *UpdateEnergyLimitContract) Reset() {
	*x = UpdateEnergyLimitContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_smart_contract_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEnergyLimitContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnergyLimitContract) ProtoMessage() {}

func (x *UpdateEnergyLimitContract) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_smart_contract_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnergyLimitContract.ProtoReflect.Descriptor instead.
func (*UpdateEnergyLimitContract) Descriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEnergyLimitContract) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *UpdateEnergyLimitContract) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *UpdateEnergyLimitContract) GetOriginEnergyLimit() int64 {
	if x != nil {
		return x.OriginEnergyLimit
	}
	return 0
}

type SmartContractDataWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmartContract *SmartContract `protobuf:"bytes,1,opt,name=smart_contract,json=smartContract,proto3" json:"smart_contract,omitempty"`
	Runtimecode   []byte         `protobuf:"bytes,2,opt,name=runtimecode,proto3" json:"runtimecode,omitempty"`
	ContractState *ContractState `protobuf:"bytes,3,opt,name=contract_state,json=contractState,proto3" json:"contract_state,omitempty"`
}

func (x *SmartContractDataWrapper) Reset() {
	*x = SmartContractDataWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_smart_contract_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartContractDataWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartContractDataWrapper) ProtoMessage() {}

func (x *SmartContractDataWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_smart_contract_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartContractDataWrapper.ProtoReflect.Descriptor instead.
func (*SmartContractDataWrapper) Descriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{7}
}

func (x *SmartContractDataWrapper) GetSmartContract() *SmartContract {
	if x != nil {
		return x.SmartContract
	}
	return nil
}

func (x *SmartContractDataWrapper) GetRuntimecode() []byte {
	if x != nil {
		return x.Runtimecode
	}
	return nil
}

func (x *SmartContractDataWrapper) GetContractState() *ContractState {
	if x != nil {
		return x.ContractState
	}
	return nil
}

type SmartContract_ABI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entrys []*SmartContract_ABI_Entry `protobuf:"bytes,1,rep,name=entrys,proto3" json:"entrys,omitempty"`
}

func (x *SmartContract_ABI) Reset() {
	*x = SmartContract_ABI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_smart_contract_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartContract_ABI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartContract_ABI) ProtoMessage() {}

func (x *SmartContract_ABI) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_smart_contract_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartContract_ABI.ProtoReflect.Descriptor instead.
func (*SmartContract_ABI) Descriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SmartContract_ABI) GetEntrys() []*SmartContract_ABI_Entry {
	if x != nil {
		return x.Entrys
	}
	return nil
}

type SmartContract_ABI_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Anonymous       bool                                        `protobuf:"varint,1,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	Constant        bool                                        `protobuf:"varint,2,opt,name=constant,proto3" json:"constant,omitempty"`
	Name            string                                      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Inputs          []*SmartContract_ABI_Entry_Param            `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs         []*SmartContract_ABI_Entry_Param            `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Type            SmartContract_ABI_Entry_EntryType           `protobuf:"varint,6,opt,name=type,proto3,enum=protocol.SmartContract_ABI_Entry_EntryType" json:"type,omitempty"`
	Payable         bool                                        `protobuf:"varint,7,opt,name=payable,proto3" json:"payable,omitempty"`
	StateMutability SmartContract_ABI_Entry_StateMutabilityType `protobuf:"varint,8,opt,name=stateMutability,proto3,enum=protocol.SmartContract_ABI_Entry_StateMutabilityType" json:"stateMutability,omitempty"`
}

func (x *SmartContract_ABI_Entry) Reset() {
	*x = SmartContract_ABI_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_smart_contract_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartContract_ABI_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartContract_ABI_Entry) ProtoMessage() {}

func (x *SmartContract_ABI_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_smart_contract_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartContract_ABI_Entry.ProtoReflect.Descriptor instead.
func (*SmartContract_ABI_Entry) Descriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *SmartContract_ABI_Entry) GetAnonymous() bool {
	if x != nil {
		return x.Anonymous
	}
	return false
}

func (x *SmartContract_ABI_Entry) GetConstant() bool {
	if x != nil {
		return x.Constant
	}
	return false
}

func (x *SmartContract_ABI_Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SmartContract_ABI_Entry) GetInputs() []*SmartContract_ABI_Entry_Param {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *SmartContract_ABI_Entry) GetOutputs() []*SmartContract_ABI_Entry_Param {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *SmartContract_ABI_Entry) GetType() SmartContract_ABI_Entry_EntryType {
	if x != nil {
		return x.Type
	}
	return SmartContract_ABI_Entry_UnknownEntryType
}

func (x *SmartContract_ABI_Entry) GetPayable() bool {
	if x != nil {
		return x.Payable
	}
	return false
}

func (x *SmartContract_ABI_Entry) GetStateMutability() SmartContract_ABI_Entry_StateMutabilityType {
	if x != nil {
		return x.StateMutability
	}
	return SmartContract_ABI_Entry_UnknownMutabilityType
}

type SmartContract_ABI_Entry_Param struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indexed bool   `protobuf:"varint,1,opt,name=indexed,proto3" json:"indexed,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // SolidityType type = 3;
}

func (x *SmartContract_ABI_Entry_Param) Reset() {
	*x = SmartContract_ABI_Entry_Param{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_contract_smart_contract_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartContract_ABI_Entry_Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartContract_ABI_Entry_Param) ProtoMessage() {}

func (x *SmartContract_ABI_Entry_Param) ProtoReflect() protoreflect.Message {
	mi := &file_core_contract_smart_contract_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartContract_ABI_Entry_Param.ProtoReflect.Descriptor instead.
func (*SmartContract_ABI_Entry_Param) Descriptor() ([]byte, []int) {
	return file_core_contract_smart_contract_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *SmartContract_ABI_Entry_Param) GetIndexed() bool {
	if x != nil {
		return x.Indexed
	}
	return false
}

func (x *SmartContract_ABI_Entry_Param) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SmartContract_ABI_Entry_Param) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_core_contract_smart_contract_proto protoreflect.FileDescriptor

var file_core_contract_smart_contract_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f,
	0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x0f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x54, 0x72, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa0, 0x09, 0x0a, 0x0d, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x2d, 0x0a, 0x03, 0x61, 0x62, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x6d, 0x61, 0x72,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x41, 0x42, 0x49, 0x52, 0x03, 0x61,
	0x62, 0x69, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x79, 0x74, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x62, 0x79, 0x74, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x41, 0x0a,
	0x1d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x1a, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x5f, 0x65,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x11, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x74, 0x72, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0xf9, 0x05, 0x0a, 0x03, 0x41, 0x42, 0x49, 0x12, 0x39,
	0x0a, 0x06, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x41, 0x42, 0x49, 0x2e, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x73, 0x1a, 0xb6, 0x05, 0x0a, 0x05, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x3f, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x6d, 0x61,
	0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x41, 0x42, 0x49, 0x2e, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x06, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x73, 0x12, 0x41, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53,
	0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x41, 0x42, 0x49,
	0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x07, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x3f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53,
	0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x41, 0x42, 0x49,
	0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x61, 0x79, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x5f, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x75, 0x74, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x35, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2e, 0x41, 0x42, 0x49, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x4d, 0x75, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x75, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x1a, 0x49, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x71, 0x0a, 0x09,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x02, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x06, 0x22,
	0x61, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x75, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x4d, 0x75, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x75, 0x72, 0x65, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x56,
	0x69, 0x65, 0x77, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x6f, 0x6e, 0x70, 0x61, 0x79, 0x61,
	0x62, 0x6c, 0x65, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x61, 0x62, 0x6c, 0x65,
	0x10, 0x04, 0x22, 0x7a, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x5f, 0x75, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x6e, 0x65, 0x72, 0x67,
	0x79, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79,
	0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x65,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x22, 0xbb,
	0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3a, 0x0a, 0x0c, 0x6e,
	0x65, 0x77, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x6d, 0x61,
	0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x61, 0x6c, 0x6c, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x63, 0x61, 0x6c, 0x6c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x22, 0xde, 0x01, 0x0a,
	0x14, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x61, 0x6c, 0x6c,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0e, 0x63, 0x61, 0x6c, 0x6c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x62, 0x0a,
	0x10, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x42, 0x49, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x22, 0xaa, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0c, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x41, 0x0a, 0x1d, 0x63,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x1a, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x22, 0x9b,
	0x01, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2e, 0x0a, 0x13,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x5f, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x5f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xbc, 0x01, 0x0a,
	0x18, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x0e, 0x73, 0x6d, 0x61,
	0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x6d, 0x61,
	0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x0d, 0x73, 0x6d, 0x61, 0x72,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x45, 0x0a, 0x18, 0x6f,
	0x72, 0x67, 0x2e, 0x74, 0x72, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x6f, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_contract_smart_contract_proto_rawDescOnce sync.Once
	file_core_contract_smart_contract_proto_rawDescData = file_core_contract_smart_contract_proto_rawDesc
)

func file_core_contract_smart_contract_proto_rawDescGZIP() []byte {
	file_core_contract_smart_contract_proto_rawDescOnce.Do(func() {
		file_core_contract_smart_contract_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_contract_smart_contract_proto_rawDescData)
	})
	return file_core_contract_smart_contract_proto_rawDescData
}

var file_core_contract_smart_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_core_contract_smart_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_core_contract_smart_contract_proto_goTypes = []interface{}{
	(SmartContract_ABI_Entry_EntryType)(0),           // 0: protocol.SmartContract.ABI.Entry.EntryType
	(SmartContract_ABI_Entry_StateMutabilityType)(0), // 1: protocol.SmartContract.ABI.Entry.StateMutabilityType
	(*SmartContract)(nil),                            // 2: protocol.SmartContract
	(*ContractState)(nil),                            // 3: protocol.ContractState
	(*CreateSmartContract)(nil),                      // 4: protocol.CreateSmartContract
	(*TriggerSmartContract)(nil),                     // 5: protocol.TriggerSmartContract
	(*ClearABIContract)(nil),                         // 6: protocol.ClearABIContract
	(*UpdateSettingContract)(nil),                    // 7: protocol.UpdateSettingContract
	(*UpdateEnergyLimitContract)(nil),                // 8: protocol.UpdateEnergyLimitContract
	(*SmartContractDataWrapper)(nil),                 // 9: protocol.SmartContractDataWrapper
	(*SmartContract_ABI)(nil),                        // 10: protocol.SmartContract.ABI
	(*SmartContract_ABI_Entry)(nil),                  // 11: protocol.SmartContract.ABI.Entry
	(*SmartContract_ABI_Entry_Param)(nil),            // 12: protocol.SmartContract.ABI.Entry.Param
}
var file_core_contract_smart_contract_proto_depIdxs = []int32{
	10, // 0: protocol.SmartContract.abi:type_name -> protocol.SmartContract.ABI
	2,  // 1: protocol.CreateSmartContract.new_contract:type_name -> protocol.SmartContract
	2,  // 2: protocol.SmartContractDataWrapper.smart_contract:type_name -> protocol.SmartContract
	3,  // 3: protocol.SmartContractDataWrapper.contract_state:type_name -> protocol.ContractState
	11, // 4: protocol.SmartContract.ABI.entrys:type_name -> protocol.SmartContract.ABI.Entry
	12, // 5: protocol.SmartContract.ABI.Entry.inputs:type_name -> protocol.SmartContract.ABI.Entry.Param
	12, // 6: protocol.SmartContract.ABI.Entry.outputs:type_name -> protocol.SmartContract.ABI.Entry.Param
	0,  // 7: protocol.SmartContract.ABI.Entry.type:type_name -> protocol.SmartContract.ABI.Entry.EntryType
	1,  // 8: protocol.SmartContract.ABI.Entry.stateMutability:type_name -> protocol.SmartContract.ABI.Entry.StateMutabilityType
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_core_contract_smart_contract_proto_init() }
func file_core_contract_smart_contract_proto_init() {
	if File_core_contract_smart_contract_proto != nil {
		return
	}
	file_core_Tron_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_core_contract_smart_contract_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_smart_contract_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_smart_contract_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSmartContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_smart_contract_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerSmartContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_smart_contract_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearABIContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_smart_contract_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSettingContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_smart_contract_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEnergyLimitContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_smart_contract_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartContractDataWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_smart_contract_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartContract_ABI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_smart_contract_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartContract_ABI_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_contract_smart_contract_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartContract_ABI_Entry_Param); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_contract_smart_contract_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_contract_smart_contract_proto_goTypes,
		DependencyIndexes: file_core_contract_smart_contract_proto_depIdxs,
		EnumInfos:         file_core_contract_smart_contract_proto_enumTypes,
		MessageInfos:      file_core_contract_smart_contract_proto_msgTypes,
	}.Build()
	File_core_contract_smart_contract_proto = out.File
	file_core_contract_smart_contract_proto_rawDesc = nil
	file_core_contract_smart_contract_proto_goTypes = nil
	file_core_contract_smart_contract_proto_depIdxs = nil
}
