// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package nft_candy_machine_v2

import (
	"github.com/emresenyuva/go-wallet-sdk/coins/solana/base"
)

type WhitelistMintSettings struct {
	Mode          WhitelistMintMode
	Mint          base.PublicKey
	Presale       bool
	DiscountPrice *uint64 `bin:"optional"`
}

func (obj WhitelistMintSettings) MarshalWithEncoder(encoder *base.Encoder) (err error) {
	// Serialize `Mode` param:
	err = encoder.Encode(obj.Mode)
	if err != nil {
		return err
	}
	// Serialize `Mint` param:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return err
	}
	// Serialize `Presale` param:
	err = encoder.Encode(obj.Presale)
	if err != nil {
		return err
	}
	// Serialize `DiscountPrice` param (optional):
	{
		if obj.DiscountPrice == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.DiscountPrice)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

type CandyMachineData struct {
	Uuid                  string
	Price                 uint64
	Symbol                string
	SellerFeeBasisPoints  uint16
	MaxSupply             uint64
	IsMutable             bool
	RetainAuthority       bool
	GoLiveDate            *int64       `bin:"optional"`
	EndSettings           *EndSettings `bin:"optional"`
	Creators              []Creator
	HiddenSettings        *HiddenSettings        `bin:"optional"`
	WhitelistMintSettings *WhitelistMintSettings `bin:"optional"`
	ItemsAvailable        uint64
	Gatekeeper            *GatekeeperConfig `bin:"optional"`
}

func (obj CandyMachineData) MarshalWithEncoder(encoder *base.Encoder) (err error) {
	// Serialize `Uuid` param:
	err = encoder.Encode(obj.Uuid)
	if err != nil {
		return err
	}
	// Serialize `Price` param:
	err = encoder.Encode(obj.Price)
	if err != nil {
		return err
	}
	// Serialize `Symbol` param:
	err = encoder.Encode(obj.Symbol)
	if err != nil {
		return err
	}
	// Serialize `SellerFeeBasisPoints` param:
	err = encoder.Encode(obj.SellerFeeBasisPoints)
	if err != nil {
		return err
	}
	// Serialize `MaxSupply` param:
	err = encoder.Encode(obj.MaxSupply)
	if err != nil {
		return err
	}
	// Serialize `IsMutable` param:
	err = encoder.Encode(obj.IsMutable)
	if err != nil {
		return err
	}
	// Serialize `RetainAuthority` param:
	err = encoder.Encode(obj.RetainAuthority)
	if err != nil {
		return err
	}
	// Serialize `GoLiveDate` param (optional):
	{
		if obj.GoLiveDate == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.GoLiveDate)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `EndSettings` param (optional):
	{
		if obj.EndSettings == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.EndSettings)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `Creators` param:
	err = encoder.Encode(obj.Creators)
	if err != nil {
		return err
	}
	// Serialize `HiddenSettings` param (optional):
	{
		if obj.HiddenSettings == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.HiddenSettings)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `WhitelistMintSettings` param (optional):
	{
		if obj.WhitelistMintSettings == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.WhitelistMintSettings)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `ItemsAvailable` param:
	err = encoder.Encode(obj.ItemsAvailable)
	if err != nil {
		return err
	}
	// Serialize `Gatekeeper` param (optional):
	{
		if obj.Gatekeeper == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.Gatekeeper)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

type GatekeeperConfig struct {
	GatekeeperNetwork base.PublicKey
	ExpireOnUse       bool
}

func (obj GatekeeperConfig) MarshalWithEncoder(encoder *base.Encoder) (err error) {
	// Serialize `GatekeeperNetwork` param:
	err = encoder.Encode(obj.GatekeeperNetwork)
	if err != nil {
		return err
	}
	// Serialize `ExpireOnUse` param:
	err = encoder.Encode(obj.ExpireOnUse)
	if err != nil {
		return err
	}
	return nil
}

type EndSettings struct {
	EndSettingType EndSettingType
	Number         uint64
}

func (obj EndSettings) MarshalWithEncoder(encoder *base.Encoder) (err error) {
	// Serialize `EndSettingType` param:
	err = encoder.Encode(obj.EndSettingType)
	if err != nil {
		return err
	}
	// Serialize `Number` param:
	err = encoder.Encode(obj.Number)
	if err != nil {
		return err
	}
	return nil
}

type HiddenSettings struct {
	Name string
	Uri  string
	Hash [32]uint8
}

func (obj HiddenSettings) MarshalWithEncoder(encoder *base.Encoder) (err error) {
	// Serialize `Name` param:
	err = encoder.Encode(obj.Name)
	if err != nil {
		return err
	}
	// Serialize `Uri` param:
	err = encoder.Encode(obj.Uri)
	if err != nil {
		return err
	}
	// Serialize `Hash` param:
	err = encoder.Encode(obj.Hash)
	if err != nil {
		return err
	}
	return nil
}

type ConfigLine struct {
	Name string
	Uri  string
}

func (obj ConfigLine) MarshalWithEncoder(encoder *base.Encoder) (err error) {
	// Serialize `Name` param:
	err = encoder.Encode(obj.Name)
	if err != nil {
		return err
	}
	// Serialize `Uri` param:
	err = encoder.Encode(obj.Uri)
	if err != nil {
		return err
	}
	return nil
}

type Creator struct {
	Address  base.PublicKey
	Verified bool
	Share    uint8
}

func (obj Creator) MarshalWithEncoder(encoder *base.Encoder) (err error) {
	// Serialize `Address` param:
	err = encoder.Encode(obj.Address)
	if err != nil {
		return err
	}
	// Serialize `Verified` param:
	err = encoder.Encode(obj.Verified)
	if err != nil {
		return err
	}
	// Serialize `Share` param:
	err = encoder.Encode(obj.Share)
	if err != nil {
		return err
	}
	return nil
}

type WhitelistMintMode uint8

const (
	WhitelistMintModeBurnEveryTime WhitelistMintMode = iota
	WhitelistMintModeNeverBurn
)

func (value WhitelistMintMode) String() string {
	switch value {
	case WhitelistMintModeBurnEveryTime:
		return "BurnEveryTime"
	case WhitelistMintModeNeverBurn:
		return "NeverBurn"
	default:
		return ""
	}
}

type EndSettingType uint8

const (
	EndSettingTypeDate EndSettingType = iota
	EndSettingTypeAmount
)

func (value EndSettingType) String() string {
	switch value {
	case EndSettingTypeDate:
		return "Date"
	case EndSettingTypeAmount:
		return "Amount"
	default:
		return ""
	}
}
